import React from 'react';
import {AbsoluteFill,Audio,Img,Sequence,staticFile,useCurrentFrame,interpolate} from 'remotion';
import {FONT_BODY,FONT_DISPLAY} from '../../fonts';
const captions=[{"start": 110, "end": 172, "text": "With one careful click, Pip"}, {"start": 172, "end": 232, "text": "joined both ends. Then came"}, {"start": 232, "end": 268, "text": "the longest second of the"}, {"start": 268, "end": 283, "text": "night."}, {"start": 325, "end": 373, "text": "The beacon swept across the"}, {"start": 373, "end": 445, "text": "waves. The boat answered and"}, {"start": 445, "end": 508, "text": "turned toward home. Pip did"}, {"start": 508, "end": 563, "text": "not need more power; just"}, {"start": 563, "end": 606, "text": "one small connection."}];
export const compositionConfig = {id:'LighthouseShort',durationInSeconds:20.400000000,fps:30,width:1080,height:1920};
export default function Shot(){const f=useCurrentFrame();const intro=f<105;const home=f>=318;const caption=captions.find(c=>f>=c.start&&f<=c.end);const join=f>=139;
return <AbsoluteFill style={{background:'#0c2530',fontFamily:FONT_BODY,color:'#fff2d6'}}><Sequence from={105}><Audio src={staticFile('projects/lighthouse/short-audio.wav')}/></Sequence>
<div style={{position:'absolute',top:140,left:80,right:80,color:'#ffc36e',fontSize:27,letterSpacing:5}}>THE LITTLE LIGHTHOUSE</div>
<div style={{position:'absolute',top:220,left:80,right:80,fontFamily:FONT_DISPLAY,fontSize:79,lineHeight:1.12,fontWeight:700}}>{intro?'One boat waiting. One loose cable.':home?'A way home.':'One careful click.'}</div>
<div style={{position:'absolute',top:520,left:45,right:45,height:750,borderRadius:42,overflow:'hidden'}}><Img src={staticFile('projects/lighthouse/'+(home?'restored':intro?'dark':'pip')+'.png')} style={{width:'100%',height:'100%',objectFit:'cover',transform:`scale(${1+Math.min(f,600)/16000})`}}/></div>
{!intro&&!home&&<svg width="920" height="150" style={{position:'absolute',left:80,top:1330}}><path d={join?'M30 75H890':'M30 75H385M535 75H890'} stroke="#73bcca" strokeWidth="16"/><rect x={join?422:362} y="45" width="38" height="60" rx="7" fill="#ffc36e"/><rect x={join?460:520} y="45" width="38" height="60" rx="7" fill="#ffc36e"/></svg>}
<div style={{position:'absolute',left:80,right:80,top:1510,fontSize:54,textAlign:'center',lineHeight:1.35,fontWeight:600}}>{intro?'A small story about finding the missing connection.':caption?.text|| (home?'Small connections. Brighter nights.':'')}</div>
<div style={{position:'absolute',left:80,bottom:110,fontSize:23,color:'#a8c4c9'}}>An original illustrated story</div></AbsoluteFill>}
