"""Synthetic frame-numbered video with sample-known pulses; contains no personal data."""
import hashlib
import json
import math
import subprocess
import tempfile
import wave
from array import array
from fractions import Fraction
from pathlib import Path
from PIL import Image, ImageDraw

def make_clock_clip(out: Path, fps: str, seconds: int) -> Path:
    rate = Fraction(fps)
    if rate <= 0 or seconds <= 0:
        raise ValueError('Positive FPS and duration required')
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    frames = math.ceil(rate * seconds)
    with tempfile.TemporaryDirectory() as tmp:
        wav = Path(tmp) / 'pulses.wav'
        samples = array('h', (int(10000 * math.sin(2 * math.pi * 1000 * i / 48000)) if i % 48000 < 2400 else 0 for i in range(seconds * 48000)))
        with wave.open(str(wav), 'wb') as f:
            f.setparams((1, 2, 48000, 0, 'NONE', 'not compressed'))
            f.writeframes(samples.tobytes())
        with subprocess.Popen(['ffmpeg', '-y', '-v', 'error', '-f', 'rawvideo', '-pixel_format', 'rgb24', '-video_size', '640x360',
                               '-framerate', str(rate), '-i', 'pipe:0', '-i', str(wav), '-c:v', 'libx264', '-pix_fmt', 'yuv420p',
                               '-c:a', 'aac', '-movflags', '+faststart', str(out)], stdin=subprocess.PIPE) as proc:
            for n in range(frames):
                flash = (Fraction(n, 1) / rate) % 1 < Fraction(1, 20)
                im = Image.new('RGB', (640, 360), '#ffffff' if flash else '#122c3a')
                draw = ImageDraw.Draw(im)
                draw.text((32, 150), f'FRAME {n:06d}   FPS {rate}   TIME {float(n / rate):.3f}', fill='#00bb88', font_size=23)
                proc.stdin.write(im.tobytes())
            proc.stdin.close()
            if proc.wait() != 0:
                raise RuntimeError('Fixture encoding failed')
    out.with_suffix('.json').write_text(json.dumps({'schema_version': 1, 'fps': str(rate), 'frames': frames,
        'sample_rate': 48000, 'pulse_samples': list(range(0, seconds * 48000, 48000)),
        'sha256': hashlib.sha256(out.read_bytes()).hexdigest(), 'source': 'synthetic, generated by tools.fixture_media'}, indent=2))
    return out
