"""Create the local viewing room and update the written execution record."""
import html,json,re
from pathlib import Path
R=Path(__file__).resolve().parents[2];P=R/'videos/lighthouse';W=P/'work';O=P/'output'
def main():
    delivery=json.loads((W/'delivery-verification.json').read_text());notes=json.loads((R/'productions/lighthouse/production-notes.json').read_text())
    horizontal=delivery['artifacts'][0];vertical=delivery['artifacts'][1]
    thumbs=''.join(f'<figure><img src="packaging/thumbs/{x}.jpg" alt="Thumbnail {x}"><figcaption>Option {x} · {label}</figcaption></figure>' for x,label in [('A','One tiny fix'),('B','Home again'),('C','A light away')])
    rows=[('Local narration + cleanup','Five Qwen voice beats, DeepFilterNet; two initial takes preserved and replaced after invalid alignment.'),('Recognition + editing','97 words retained. Native preview and HEVC master, sample-based mapping and independent recognition.'),('Images + reference edits','Four original local story images; the incorrectly glowing dark-lighthouse take was corrected.'),('Remotion + effects','Fictional screencast, animated cable connection, title/ending alpha overlays, split, pause insert, crossfade, punch-in and grade.'),('Sound + music','Three procedural cues, original deterministic score, ducked mix and separate aligned stems.'),('Packaging + short','Three untested thumbnail options, descriptions, timed captions and a standalone vertical adaptation.'),('PAIR','See execution report for the actual bounded local response outcome; no pooled memory or additional node used.'),('Editor + tracker','Raw proxy, browser editor access and local project tracking.'),('Delivery QA','Decoded exports, exact frame counts, loudness/true peak, source/master audio correlation, artifact hashes.'),('Retained / deferred','No publication or publication tests, hosted generation, personal avatar, large-model video, arbitrary generated music/SFX or multi-node setup.')]
    table=''.join(f'<tr><th>{html.escape(a)}</th><td>{html.escape(b)}</td></tr>' for a,b in rows)
    page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>The Little Lighthouse — Viewing Room</title><style>
:root{{color-scheme:dark}}*{{box-sizing:border-box}}body{{margin:0;background:#0b202b;color:#f4efdf;font:17px/1.65 system-ui}}main{{max-width:1240px;margin:auto;padding:65px 30px}}.eyebrow{{color:#f4bc75;letter-spacing:4px;font-size:13px}}h1{{font-size:clamp(42px,6vw,76px);line-height:1.05;margin:20px 0}}h2{{font-size:30px;margin:55px 0 20px}}.lede{{max-width:780px;color:#bed0d0;font-size:22px}}video{{width:100%;border-radius:18px;background:#020d12}}.meta{{color:#b4cccc;font-size:14px}}a{{color:#ffd195;text-underline-offset:4px}}.grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}}figure{{margin:0}}img{{width:100%;border-radius:12px}}figcaption{{color:#b4cccc;font-size:14px;padding:8px 0}}.short{{display:grid;grid-template-columns:380px 1fr;gap:55px;align-items:start}}.short video{{max-height:660px}}table{{width:100%;border-collapse:collapse}}th,td{{padding:17px 12px;border-bottom:1px solid #2c4650;vertical-align:top;text-align:left}}th{{color:#ffd195;width:26%}}.note{{border-left:3px solid #f4bc75;padding:12px 22px;background:#142e38}}@media(max-width:700px){{.grid,.short{{grid-template-columns:1fr}}main{{padding:35px 20px}}th{{width:35%}}}}
</style></head><body><main><div class="eyebrow">AN ORIGINAL LOCAL PRODUCTION</div><h1>The Little Lighthouse</h1><p class="lede">One boat waiting. One loose connection. A small keeper finds the way to bring the harbor home.</p>
<video controls preload="metadata" poster="packaging/thumbs/B.jpg"><source src="output/The%20Little%20Lighthouse.mp4" type="video/mp4"><track kind="captions" src="output/The%20Little%20Lighthouse.vtt" srclang="en" label="English"></video>
<p class="meta">{horizontal['video_duration_s']:.2f} seconds · 1920 × 1080 · 30 fps · {horizontal['frames']} frames · {horizontal['loudness']['input_i']} LUFS · {horizontal['loudness']['input_tp']} dBTP</p>
<p><a href="output/The%20Little%20Lighthouse.mp4" download>Download film</a> · <a href="../../plan/The%20Little%20Lighthouse%20%E2%80%94%20Production%20Specification.html">Production specification</a> · <a href="../../productions/lighthouse/Execution%20Report.md">Execution report</a></p>
<h2>A smaller window, a complete story</h2><div class="short"><video controls preload="metadata"><source src="output/The%20Little%20Lighthouse%20%E2%80%94%20Vertical.mp4" type="video/mp4"></video><div><p>The {vertical['video_duration_s']:.1f}-second vertical adaptation adds its own opening context, reframes the illustrations, and carries the repair through to the return of the light.</p><p>It includes readable timed captions and the finished sound mix.</p><a href="output/The%20Little%20Lighthouse%20%E2%80%94%20Vertical.mp4" download>Download vertical film</a></div></div>
<h2>Three ways into the same story</h2><div class="grid">{thumbs}</div><p class="meta">One fixed title: The Little Robot Who Brought the Light Back. These options have not been audience-tested.</p>
<h2>The production behind the story</h2><table>{table}</table>
<h2>Editable handoff</h2><p><a href="output/voice-track.wav">Narration stem</a> · <a href="output/sfx-track.wav">Sound-effects stem</a> · <a href="output/music-track.wav">Music stem</a> · <a href="output/The%20Little%20Lighthouse.srt">Subtitles</a> · <a href="packaging/description.txt">Description</a> · <a href="http://127.0.0.1:8773">Open cut editor</a></p>
<p class="note">Technical checks and visual frame review are complete. Independent speech timing flags and listening/creative review remain explicitly documented. This run does not claim human listening acceptance. Nothing was uploaded or published.</p></main></body></html>'''
    (P/'review.html').write_text(page)
if __name__=='__main__':main()
